### ISSUE TITLE
No runnable methods with Enclosed and PowerMockRunner

### ISSUE THREAD

**Issue by moh-sushi** [powermock/powermock#733] opened 2016-12-12 11:58 UTC
Hi PowerMock-Team,

i am getting an exception "No runnable methods" while using this template

```

@RunWith(Enclosed.class)
public class XXXX {

@RunWith(PowerMockRunner.class)
public static class Method_To_Test_Class {
       
        @Test
        public void no_results_found throws Exception {
              // no prefix of test for method name
        }
}
// further public static classes for other methods are available

}

```

If the method "no_results_found" has the prefix "test" , no exception will be thrown.

As far as i can see while debugging PowerMock, the method "getTestMethods" in class "PowerMockJUnit4MethodValidator" contains this issue.

usage of :
- junit 4.12
- powermock 1.6.6
- JDK 8 u112 

an issue at my side with using PowerMock or a bug?

Thanks!

**Comment by thekingnothing** [comment] 2016-12-27 09:38
For junit before 4th version it's right behaviour, but In case of junit4 it's a bug. Looks like the `PowerMockJUnit4MethodValidator` doesn't correctly follow junit4 method name.

**Comment by rockydcoder** [comment] 2017-03-12 17:55
Hi @thekingnothing , can I take this up?

**Comment by thekingnothing** [comment] 2017-03-12 18:00
@rockydcoder, yeah, of  course you may take this up. I'll be really appreciate for help.

**Comment by rockydcoder** [comment] 2017-03-15 04:08
Hey @thekingnothing, this is my first OSS contribution ever so I am really excited about it. But I may need a little guidance. Is there any test class that tests `PowerMockJUnit4MethodValidator`? I looked at the test classes but did not find any. And is there any tip that can help me get started on this issue?

**Comment by thekingnothing** [comment] 2017-03-16 06:31
@rockydcoder, the class locates in `powermock-modules` module and as many of classes in these modules it doesn't have dedicated test. They are tested indirectly by checking that feature is working. Tests for junit modules (regardless mocking framework) are located in  [`test/junit`](https://github.com/powermock/powermock/tree/master/tests/junit4/src).
You may find package `samples.powermockito.junit4.bugs`. Here you need to add sub-package which will check case from this bug.  

Also you may create a new test for `PowerMockJUnit4MethodValidator`.

**Comment by thekingnothing** [comment] 2017-03-18 08:38
Thanks @rockydcoder for test case. 

@moh-sushi, we cannot reproduce your issue. So I close the issue.

**Closed by thekingnothing** 2017-03-18 08:38 UTC
Labels: 1 - Ready <= 7, component:junit, for new contributors
