### ISSUE TITLE
[Regression]  @Mock annotation has no effect if there is more than 1 field of the same type and fieldName is not set

### ISSUE THREAD

**Issue by ijuma** [powermock/powermock#828] opened 2017-08-04 08:14 UTC
What steps will reproduce the problem?

Run the following code with PowerMock 1.6.5, 1.6.6, 1.7.0:

```java
package org.apache.kafka.connect.runtime;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.powermock.api.easymock.annotation.Mock;
import org.powermock.core.classloader.annotations.PowerMockIgnore;
import org.powermock.core.classloader.annotations.PrepareForTest;
import org.powermock.modules.junit4.PowerMockRunner;

import static org.junit.Assert.assertNotNull;

@RunWith(PowerMockRunner.class)
@PrepareForTest(WorkerSinkTask.class)
@PowerMockIgnore("javax.management.*")
public class PowerMockRegression {

    public interface Foo {}

    @Mock
    private Foo foo1;
    @Mock
    private Foo foo2;

    @Test
    public void testStartPaused() throws Exception {
        assertNotNull(foo1);
        assertNotNull(foo1);
    }

}
```

`foo1` and `foo2` will be `null` because `DefaultInjectFieldSearcher.findField` returns `null` if there is more than 1 field with the same type without a qualifier.

```java
public Field findField(Object instance, MockMetadata mockMetadata) {
        Set<Field> candidates = Whitebox.getFieldsAnnotatedWith(instance, mockMetadata.getAnnotation());
        if (candidates.size() == 1) {
            return candidates.iterator().next();
        }
        candidates = filterByQualifier(candidates, mockMetadata.getQualifier());
        if (candidates.size() == 1) {
            return candidates.iterator().next();
        }
        candidates = filterByType(candidates, mockMetadata.getType());
        if (candidates.size() == 1) {
            return candidates.iterator().next();
        }
        return null;
    }
```

The workaround is to set `fieldName` in the Mock annotation. However, we should ideally check the field name which is available in `AnnotationMockMetadata`, which is the runtime type of `MockMetadata` in this case.

The workaround was not necessary in PowerMock 1.6.4.

What is the expected output?

The fields with the Mock annotation should be non-null.

What do you see instead?

The fields with the Mock annotation are null.

What version of the product are you using?

PowerMock 1.6.5, 1.6.6, 1.7.0.

**Comment by ijuma** [comment] 2017-08-04 08:42
It looks like the logic was changed in the following commit:

https://github.com/powermock/powermock/commit/dc3054670e42cba233aa0359eab84c786b444f04#diff-140c690de4c21768e3d9333a8e31b109L83

**Comment by thekingn0thing** [comment] 2017-08-05 07:37
Duplicate of #755

**Closed as completed** 2017-08-05 07:38 UTC
Labels: duplicate

**Comment by ijuma** [comment] 2017-08-05 07:40
Thanks, I missed it when searching.
